In [2]:
pip install sentencepiece

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 852.7 kB/s eta 0:00:0000:0100:01
Note: you may need to restart the kernel to use updated packages.


In [3]:
pip install tf-keras

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 190.4 kB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.4/45.4 kB 551.2 kB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 803.7 kB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 589.8/589.8 MB 2.1 MB/s eta 0:00:0000:0100:05m
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.7/133.7 kB 3.6 MB/s eta 0:00:00:--:--
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 1.5 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 2.4 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 2.5 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 2.8 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.5/24.5 MB 2.9 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 1.1 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

In [4]:
from transformers import XLNetTokenizer, TFXLNetModel

# Use the correct model identifier from Hugging Face Model Hub
model_name = 'xlnet-large-cased'

# Load the tokenizer and model
tokenizer = XLNetTokenizer.from_pretrained(model_name)
model = TFXLNetModel.from_pretrained(model_name)

# Example input text
input_text = "Hello, how are you?"

# Tokenize input
inputs = tokenizer(input_text, return_tensors='tf')

# Get model outputs
outputs = model(inputs)

print(outputs)

/opt/conda/lib/python3.11/site-packages/tf_keras/src/initializers/initializers.py:121: UserWarning: The initializer TruncatedNormal is unseeded and being called multiple times, which will return identical values each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initializer instance more than once.
  warnings.warn(
Some layers from the model checkpoint at xlnet-large-cased were not used when initializing TFXLNetModel: ['lm_loss']
- This IS expected if you are initializing TFXLNetModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFXLNetModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFXLN

TFXLNetModelOutput(last_hidden_state=<tf.Tensor: shape=(1, 9, 1024), dtype=float32, numpy=
array([[[-1.6709992 , -0.92030835, -1.1942148 , ..., -1.6724994 ,
          0.70507467,  1.7064161 ],
        [ 0.39474154, -0.11975965, -0.04046227, ..., -0.5282675 ,
         -1.9147506 , -0.1750461 ],
        [-1.5442853 , -1.2874888 ,  0.92295545, ..., -0.36155528,
         -0.4873641 , -1.7736564 ],
        ...,
        [ 0.92353   , -1.45275   , -0.5797529 , ...,  0.29486322,
         -1.7598855 , -3.4396791 ],
        [-0.5873277 , -0.72206646, -0.07481501, ...,  1.6026444 ,
          0.45974806,  1.1922643 ],
        [-1.2288444 , -0.98621655, -0.9448048 , ..., -0.3093344 ,
         -0.42924875,  2.2952054 ]]], dtype=float32)>, mems=(<tf.Tensor: shape=(9, 1, 1024), dtype=float32, numpy=
array([[[-0.02717384,  0.04925968, -0.01368891, ..., -0.01682383,
         -0.02933594, -0.00296901]],

       [[ 0.06611059, -0.0034283 , -0.03228189, ..., -0.02002379,
          0.03210833, -0.05285485]]

In [4]:
pip install transformers tensorflow tensorflow-datasets

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.8/43.8 kB 116.1 kB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.9/40.9 kB 528.4 kB/s eta 0:00:00:--:--
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 918.8 kB/s eta 0:00:00:0100:010m/9.1 MB 1.9 MB/s eta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 628.9 kB/s eta 0:00:00:0100:010m1.1 MB/s eta 0:00:05
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 4.2 MB/s eta 0:00:00a 0:00:01m
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 156.1/156.1 kB 3.3 MB/s eta 0:00:00 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 401.2/401.2 kB 3.7 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 785.0/785.0 kB 4.7 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 4.0 MB/s eta 0:00:00a 0:00:01m
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 4.7 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

In [5]:
pip install tf-keras

Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install sentencepiece

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 1.1 MB/s eta 0:00:0000:0100:010m
Note: you may need to restart the kernel to use updated packages.


In [1]:
pip install --upgrade jupyter ipywidgets

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.4/139.4 kB 566.8 kB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 215.0/215.0 kB 749.3 kB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 703.6 kB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 123.4/123.4 kB 1.6 MB/s eta 0:00:00 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.5/93.5 kB 799.8 kB/s eta 0:00:00:0100:01
Note: you may need to restart the kernel to use updated packages.


In [6]:
pip install scikit-learn

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 174.2 kB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 5.0 MB/s eta 0:00:0000:0100:01m
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 301.8/301.8 kB 4.1 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.6/38.6 MB 3.9 MB/s eta 0:00:0000:0100:01
Note: you may need to restart the kernel to use updated packages.


In [8]:
!pip install pandas

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.0/13.0 MB 5.9 MB/s eta 0:00:0000:0100:01m
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 345.4/345.4 kB 4.1 MB/s eta 0:00:00a 0:00:01


In [7]:
pip install openpyxl

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 250.0/250.0 kB 360.1 kB/s eta 0:00:00a 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [3]:
import os
import pandas as pd
from sklearn.model_selection import train_test_split
from transformers import XLNetTokenizer, TFXLNetForSequenceClassification
import tensorflow as tf
import gc

# Load the dataset
file_path = "/home/jovyan/work/preprocessed_reviews.xlsx"
print("File exists:", os.path.isfile(file_path))

# Load the entire dataset
dataset = pd.read_excel(file_path)

# Reduce batch size
batch_size = 4

# Split data into training and validation sets
train_texts, val_texts, train_labels, val_labels = train_test_split(dataset['texts'].tolist(), dataset['labels'].tolist(), test_size=0.2, random_state=42)

# Clear the dataset from memory
del dataset
gc.collect()

# Load the XLNet tokenizer
tokenizer = XLNetTokenizer.from_pretrained('xlnet-base-cased')

# Set max_length for tokenization
max_length = 128

# Tokenize input texts in chunks to manage memory
def tokenize_texts(texts, tokenizer, max_length=128):
    input_ids = []
    attention_mask = []
    for i in range(0, len(texts), batch_size):
        chunk = texts[i:i+batch_size]
        encodings = tokenizer(chunk, truncation=True, padding='max_length', max_length=max_length)
        input_ids.extend(encodings['input_ids'])
        attention_mask.extend(encodings['attention_mask'])
        # Clear memory
        del encodings
        gc.collect()
    return {'input_ids': input_ids, 'attention_mask': attention_mask}

train_encodings = tokenize_texts(train_texts, tokenizer, max_length=max_length)
val_encodings = tokenize_texts(val_texts, tokenizer, max_length=max_length)

# Create TensorFlow datasets
train_dataset = tf.data.Dataset.from_tensor_slices((
    dict(train_encodings),
    train_labels
)).shuffle(1000).batch(batch_size)

val_dataset = tf.data.Dataset.from_tensor_slices((
    dict(val_encodings),
    val_labels
)).batch(batch_size)

# Clear unnecessary variables
del train_texts, val_texts, train_labels, val_labels, train_encodings, val_encodings
gc.collect()

# Define the model architecture
model = TFXLNetForSequenceClassification.from_pretrained('xlnet-base-cased', num_labels=2)

# Compile the model
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=2e-5),
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

# Train the model
history = model.fit(train_dataset,
                    validation_data=val_dataset,
                    epochs=3)

File exists: True


/opt/conda/lib/python3.11/site-packages/tf_keras/src/initializers/initializers.py:121: UserWarning: The initializer TruncatedNormal is unseeded and being called multiple times, which will return identical values each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initializer instance more than once.
  warnings.warn(
Some layers from the model checkpoint at xlnet-base-cased were not used when initializing TFXLNetForSequenceClassification: ['lm_loss']
- This IS expected if you are initializing TFXLNetForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFXLNetForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a Be

Epoch 1/3
Cause: for/else statement not yet supported
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Cause: for/else statement not yet supported
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


2024-05-18 18:16:20.647015: E tensorflow/core/util/util.cc:131] oneDNN supports DT_INT32 only on platforms with AVX-512. Falling back to the default Eigen-based implementation if present.


776/776 [==============================] - 5777s 7s/step - loss: 0.4652 - accuracy: 0.8247 - val_loss: 0.4539 - val_accuracy: 0.8325
Epoch 2/3
776/776 [==============================] - 5299s 7s/step - loss: 0.4644 - accuracy: 0.8269 - val_loss: 0.4530 - val_accuracy: 0.8325
Epoch 3/3
776/776 [==============================] - 4295s 6s/step - loss: 0.4636 - accuracy: 0.8253 - val_loss: 0.4698 - val_accuracy: 0.8325


In [4]:
pip install transformers tensorflow pandas scikit-learn

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.8/43.8 kB 202.1 kB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.9/40.9 kB 3.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 481.0 kB/s eta 0:00:00:--:--
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.4/45.4 kB 650.5 kB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 320.8 kB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 589.8/589.8 MB 231.0 kB/s eta 0:00:0000:010:15m
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 178.1 kB/s eta 0:00:0000:0100:02
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.7/133.7 kB 398.9 kB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 1.2 MB/s eta 0:00:00-:--:--
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 285.6 kB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 547.3 kB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

In [2]:
pip install --upgrade transformers

Note: you may need to restart the kernel to use updated packages.


In [ ]:
import os
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from transformers import XLNetTokenizer, TFXLNetForSequenceClassification

# Load the dataset
file_path = "/home/jovyan/work/preprocessed_reviews.xlsx"
print("File exists:", os.path.isfile(file_path))

# Load the entire dataset
dataset = pd.read_excel(file_path)

# Reduce batch size
batch_size = 4

# Split data into training and validation sets
train_texts, val_texts, train_labels, val_labels = train_test_split(dataset['texts'].tolist(), dataset['labels'].tolist(), test_size=0.2, random_state=42)

# Clear the dataset from memory
del dataset

# Load the XLNet tokenizer
tokenizer = XLNetTokenizer.from_pretrained('xlnet-base-cased')

# Set max_length for tokenization
max_length = 128

# Tokenize input texts in chunks to manage memory
def tokenize_texts(texts, tokenizer, max_length=128):
    input_ids = []
    attention_mask = []
    for i in range(0, len(texts), batch_size):
        chunk = texts[i:i+batch_size]
        encodings = tokenizer(chunk, truncation=True, padding='max_length', max_length=max_length)
        input_ids.extend(encodings['input_ids'])
        attention_mask.extend(encodings['attention_mask'])
    return {'input_ids': input_ids, 'attention_mask': attention_mask}

train_encodings = tokenize_texts(train_texts, tokenizer, max_length=max_length)
val_encodings = tokenize_texts(val_texts, tokenizer, max_length=max_length)

# Create TensorFlow datasets
train_dataset = tf.data.Dataset.from_tensor_slices((
    train_encodings,
    train_labels
)).shuffle(1000).batch(batch_size)

val_dataset = tf.data.Dataset.from_tensor_slices((
    val_encodings,
    val_labels
)).batch(batch_size)

# Define the XLNet model architecture
xlnet_model = TFXLNetForSequenceClassification.from_pretrained('xlnet-base-cased', num_labels=2)

# Define additional layers for classification
dense_layer1 = tf.keras.layers.Dense(512, activation='relu')
dropout_layer1 = tf.keras.layers.Dropout(0.5)
dense_layer2 = tf.keras.layers.Dense(256, activation='relu')
dropout_layer2 = tf.keras.layers.Dropout(0.3)
output_layer = tf.keras.layers.Dense(2, activation='softmax')

# Build the model
inputs = tf.keras.Input(shape=(max_length,), dtype=tf.int32, name="input_ids")
input_masks = tf.keras.Input(shape=(max_length,), dtype=tf.int32, name="attention_mask")
xlnet_output = xlnet_model({'input_ids': inputs, 'attention_mask': input_masks})
logits = xlnet_output.logits
x = tf.keras.layers.Reshape((-1, logits.shape[-1]))(logits)  # Reshape logits tensor
x = tf.keras.layers.GlobalAveragePooling1D()(x)
x = dense_layer1(x)
x = dropout_layer1(x)
x = dense_layer2(x)
x = dropout_layer2(x)
outputs = output_layer(x)

# Compile the model
model = tf.keras.Model(inputs=[inputs, input_masks], outputs=outputs)
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=2e-5),
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

# Train the model
history = model.fit(train_dataset,
                    validation_data=val_dataset,
                    epochs=1)

# Save the improved model
model.save("/home/jovyan/work/improved_xlnet_model")

# Test a sentence with the improved model
test_sentence = "This product is terrible!"
inputs = tokenizer(test_sentence, return_tensors="tf", truncation=True, padding='max_length', max_length=128)
output = model([inputs['input_ids'], inputs['attention_mask']])
probabilities = tf.nn.softmax(output)
probabilities_np = probabilities.numpy()
predicted_label = np.argmax(probabilities_np, axis=-1)[0]

# Print the results
label_names = ['negative', 'positive']  # Adjust according to your actual label names
print(f"Sentence: {test_sentence}")
print(f"Predicted label: {label_names[predicted_label]}")
print(f"Probabilities: {probabilities_np}")


2024-05-19 19:22:51.579857: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-05-19 19:22:51.585789: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-05-19 19:22:51.690309: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-05-19 19:22:52.223200: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-05-19 19:22:54.545744: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF

File exists: True


/opt/conda/lib/python3.11/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/opt/conda/lib/python3.11/site-packages/tf_keras/src/initializers/initializers.py:121: UserWarning: The initializer TruncatedNormal is unseeded and being called multiple times, which will return identical values each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initializer instance more than once.
  warnings.warn(
Some layers from the model checkpoint at xlnet-base-cased were not used when initializing TFXLNetForSequenceClassification: ['lm_loss']
- This IS expected if you are initializing TFXLNetForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing 

2024-05-19 19:26:27.285254: E tensorflow/core/util/util.cc:131] oneDNN supports DT_INT32 only on platforms with AVX-512. Falling back to the default Eigen-based implementation if present.


776/776 [==============================] - 3137s 4s/step - loss: 0.4704 - accuracy: 0.8012 - val_loss: 0.4233 - val_accuracy: 0.8325
